version: 2.1

orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build-and-deploy:
    docker:
      - image: 'cimg/node:14.15'
    steps:
      - node/install:
          node-version: '14.15'
      - checkout
      - aws-cli/setup
# Installing the frontend dependencies
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
# Building the frontend
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
# Deploying the frontend to AWS S3
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
# Installing the Backend dependencies
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
# Building the backend
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
# Deploying the backend to AWS Elastic Beanstalk
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          context: aws
          filters:
            branches:
              only:
                - main